import type { Theme } from './types';

/** Dark palette — adjust values when the design spec is finalized. */
export const darkTheme: Theme = {
  id: 'dark',
  colors: {
    background: '#141218',
    'error-container': '#93000a',
    error: '#ffb4ab',
    'inverse-on-surface': '#1b1b22',
    'inverse-primary': '#630ed4',
    'inverse-surface': '#f2effa',
    'on-background': '#e4e1ec',
    'on-error-container': '#ffdad6',
    'on-error': '#690005',
    'on-primary-container': '#25005a',
    'on-primary-fixed-variant': '#d2bbff',
    'on-primary-fixed': '#eaddff',
    'on-primary': '#25005a',
    'on-secondary-container': '#271900',
    'on-secondary-fixed-variant': '#ffdea8',
    'on-secondary-fixed': '#ffdea8',
    'on-secondary': '#271900',
    'on-surface-variant': '#ccc3d8',
    'on-surface': '#e4e1ec',
    'on-tertiary-container': '#3d0600',
    'on-tertiary-fixed-variant': '#ffdad3',
    'on-tertiary-fixed': '#ffdad3',
    'on-tertiary': '#ffffff',
    primary: '#d2bbff',
    'primary-container': '#5a00c6',
    'primary-fixed-dim': '#5a00c6',
    'primary-fixed': '#25005a',
    secondary: '#ffba20',
    'secondary-container': '#6b4b00',
    'secondary-fixed-dim': '#7c5800',
    'secondary-fixed': '#271900',
    'surface-bright': '#3b3842',
    'surface-container-high': '#34313b',
    'surface-container-highest': '#3f3c46',
    'surface-container-low': '#1f1d25',
    'surface-container-lowest': '#0f0d13',
    'surface-container': '#252329',
    'surface-dim': '#141218',
    'surface-tint': '#d2bbff',
    'surface-variant': '#4a4455',
    surface: '#141218',
    tertiary: '#ffb4a4',
    'tertiary-container': '#7f2a18',
    'tertiary-fixed-dim': '#8a321f',
    'tertiary-fixed': '#3d0600',
    'outline-variant': '#4a4455',
    outline: '#948fa0',
  },
};
