import type { Theme } from './types';

export const lightTheme: Theme = {
  id: 'light',
  colors: {
    'surface-container-low': '#f5f2fd',
    'error-container': '#ffdad6',
    'primary-container': '#7c3aed',
    'on-error': '#ffffff',
    tertiary: '#8a321f',
    'surface-container': '#efecf7',
    'outline-variant': '#ccc3d8',
    'on-secondary': '#ffffff',
    'inverse-surface': '#303038',
    'on-background': '#1b1b22',
    'on-tertiary-fixed': '#3d0600',
    'on-secondary-fixed-variant': '#5e4200',
    error: '#ba1a1a',
    'secondary-fixed-dim': '#ffba20',
    secondary: '#7c5800',
    'tertiary-container': '#a94934',
    background: '#fbf8ff',
    'surface-dim': '#dbd9e3',
    'on-secondary-fixed': '#271900',
    'tertiary-fixed': '#ffdad3',
    'on-error-container': '#93000a',
    'surface-container-highest': '#e4e1ec',
    'primary-fixed-dim': '#d2bbff',
    'on-surface-variant': '#4a4455',
    outline: '#7b7487',
    'on-primary-fixed-variant': '#5a00c6',
    'on-surface': '#1b1b22',
    'surface-container-high': '#e9e7f1',
    'inverse-primary': '#d2bbff',
    surface: '#fbf8ff',
    'tertiary-fixed-dim': '#ffb4a4',
    'secondary-fixed': '#ffdea8',
    'on-tertiary': '#ffffff',
    'on-primary-fixed': '#25005a',
    'inverse-on-surface': '#f2effa',
    primary: '#630ed4',
    'on-primary': '#ffffff',
    'surface-bright': '#fbf8ff',
    'on-tertiary-fixed-variant': '#7f2a18',
    'secondary-container': '#feb700',
    'on-tertiary-container': '#ffdfd8',
    'on-secondary-container': '#6b4b00',
    'surface-tint': '#732ee4',
    'primary-fixed': '#eaddff',
    'surface-variant': '#e4e1ec',
    'surface-container-lowest': '#ffffff',
    'on-primary-container': '#ede0ff',
  },
};
